### ISSUE TITLE
Add optional `name` to RunnerOptions and `NX_CACHE_NAME` env var

### ISSUE THREAD

**Issue by PayBas** [NiklasPor/nx-remotecache-custom#6]
https://github.com/NiklasPor/nx-remotecache-minio/blob/main/lib/index.ts#L55 outputs `Minio Storage` to the build logs.

In my situation it is advantageous to be able to override this name for CI/CD pipelines (connecting to a different Minio instance) using an ENV var such as `NX_CACHE_MINIO_NAME`, so that it's clearer to the users which cache is being used.

Nu hurry. Just a "nice to have".

**Comment by NiklasPor** [comment]
Hey again, thanks a lot for the contribution ❤️ 🚀  Your change is now available in:
- `nx-remotecache-custom@1.1.0`
- `nx-remotecache-azure@1.1.0`
- `nx-remotecache-minio@1.2.0`

And now I'm also thinking about moving all of them in a monorepo, so that releasing won't be such a hassle in the future 😄

**Comment by PayBas** [comment]
Thanks :). I'll update in the coming days to take advantage of this.
